fe smoke test failed

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -372,6 +372,21 @@ jobs:
       #           --request GET https://api.memstash.io/values/BackendURL_${CIRCLE_WORKFLOW_ID:0:7} \
       #           > .circleci/Backend_URL.txt
       - run:
+          name: Frontend smoke test.
+          command: |
+            # URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.us-east-1.amazonaws.com/index.html#/employees"
+            # echo " URL " $URL
+            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.us-east-1.amazonaws.com"
+              echo ${URL}
+            if curl -s ${URL} | grep "Welcome Gautam Gupta"
+            then
+              echo "Successful front-end Smoke-test but failing intentionally"
+              exit 1
+            else
+              echo "Unsuccessful front-end Smoke-test"
+              exit 1
+            fi
+      - run:
           name: Backend smoke test.
           command: |
             # url=$(cat .circleci/Backend_URL.txt)
@@ -393,21 +408,7 @@ jobs:
                 echo FAIL
                 exit 1
               fi
-      - run:
-          name: Frontend smoke test.
-          command: |
-            # URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.us-east-1.amazonaws.com/index.html#/employees"
-            # echo " URL " $URL
-            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.us-east-1.amazonaws.com"
-              echo ${URL}
-            if curl -s ${URL} | grep "Welcome Gautam Gupta"
-            then
-              echo "Successful front-end Smoke-test but failing intentionally"
-              exit 1
-            else
-              echo "Unsuccessful front-end Smoke-test"
-              exit 1
-            fi
+      
       - destroy-environment:
           workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
       - revert-migrations:
